title : MU4MES03
author: Corrado Maurini
logo: 'logo-SU.jpeg'

# Short description about the book
description: >-
  Supporting material for the slender structure class at Sorbonne Université.

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : True  
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/cmaurini/MU4MES03/
  path_to_book                : "book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

parse:
  myst_enable_extensions:
    - "amsmath"
    - "colon_fence"
    - "deflist"
    - "dollarmath"
    - "html_admonition"
    - "html_image"
    - "linkify"
    - "replacements"
    - "smartquotes"
    - "substitution"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
